name = "strategy"
description = "Property-based testing framework"
version = "0.1.0"

authors = ["Fabien Chouteau"]
maintainers = ["Fabien Chouteau <fabien.chouteau@gmail.com>"]
maintainers-logins = ["Fabien-Chouteau"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = ["test", "property", "testing"]

[[depends-on]]
gnat = ">=15"

[[actions]]
type = "test"
command = ["bash", "-lc", "./run_tests.sh"]
directory = "tests"
