name = "strategy"
description = "Property-based testing framework"
version = "0.1.0-dev"

authors = ["Fabien Chouteau"]
maintainers = ["Fabien Chouteau <fabien.chouteau@gmail.com>"]
maintainers-logins = ["Fabien-Chouteau"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = ["test", "property", "testing"]

[test]
runner = "alire"

[configuration.variables]
Enable_Oneof = { type = "Boolean", default = false }