name: Build

on:
  push
  pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - uses: alire-project/setup-alire@v5
      with:
        version: "nightly"

    - name: Build
      run: alr build

    - name: Tests
      run: alr test
